# Generated by Django 3.2.8 on 2021-10-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
            ],
        ),
    ]
